// root layout

import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className="p-5">

        {children}
        </main>
        <Toaster toastOptions={{duration: 1500}}/>
      </body>
    </html>
  );
}
